FROM vllm/vllm-openai:latest

RUN apt update && apt install -y python3 python3-pip git

RUN pip install vllm uv



COPY scripts/start_vllm.sh /start_vllm.sh
RUN chmod +x /start_vllm.sh

ENTRYPOINT ["/start_vllm.sh"]
